### PR TITLE
UKAPI Level context help functions

### PR DESCRIPTION
**Pull request by Hydraxous**
+ Added enum for level types (UKLevelType)
+ Added function for checking if the game currently has a playable level loaded (InLevel)
+ Added events for OnLevelLoad and OnLevelTypeChange

### CODE REVIEW

**Comment by Temperz87** [comment]
I'd like to know more on why you decided to use `delegate` instead of `UnityEvent` for the events, because `UKKeyBind` uses `UnityEvent` so it may be a good idea to just standardize this, but other than that looks good.

**Comment by TeamDoodz** [comment]
UnityEvents are much less efficient and convienient to use than regular c# events. The purpose of UnityEvents is that they can be serialized and assigned in the inspector, but since nothing in UMM is actually serialized there is no reason to actually use them.

**Comment by Temperz87** [comment]
Sounds good, merged.

**Comment by Hydraxous** [comment]
to quote myself for the sake of explanation "I used delegate because that's just what I'm familiar with if UnityEvent will work better I can fix it"

**Pull request merged**
